### ISSUE TITLE
请问一下：这里的 Occupancy 是什么意思？

### ISSUE THREAD

**Issue by blime4** [Tongkaio/CUDA_Learn#2]
grid_size 不小于 SM上最大同时执行的线程数/最大同时执行的线程块数 (Occupancy)

Occupancy = 实际运行的线程数 / SM 理论最大线程数
和上面说的 ： grid_size 不小于 SM上最大同时执行的线程数/最大同时执行的线程块数
请问有什么联系呢。

**Comment by Tongkaio** [comment]
感谢留言。

- Occupancy = 实际运行的线程数 / SM 理论最大线程数
- block_size要大于SM上**最大支持的线程数/最大block数量**​ 
- 一个 block 中的线程将被分配给一个SM，不会被拆分，所以 block_size 得是 SM **最大支持线程数的约数**
- 需要同时满足这两个条件才有可能达到 100% Occupancy

文中那里应该是block_size，已经补充描述 (f243bfc)。

**Comment by blime4** [comment]
感谢回答
